#!/bin/sh
#
# mkapi.sh: generate docs/API.md, an index of the library's functions
#
# The summary for each function is the first meaningful line of the comment
# block directly above it, so the source stays the single place documentation
# is written.  This is an INDEX, not a full reference: arguments, return values
# and side effects live in the source comments, which this links to.
#
# docs/API.md is committed, and CI runs `make docs` then `git diff --exit-code`
# so it cannot drift from the code.
set -e

cd "$(dirname "$0")/.."

OUT=${OUT:-docs/API.md}

# library files only.  install/runner.sh is internal to a generated installer
# and is documented in docs/INSTALLERS.md instead.
FILES=""
for f in ./*.sh; do
  case "$f" in
    *_test.sh | ./assert.sh | ./license*.sh) continue ;;
  esac
  FILES="$FILES $f"
done

# Extract "function<TAB>file<TAB>summary".
#
# Walks the contiguous comment block above each definition and takes the first
# line that is not a bare "#" separator and not merely a restatement of the
# function name.
extract() {
  # shellcheck disable=SC2086
  awk '
    /^[a-z_][a-z0-9_]*\(\) \{/ {
      fn = $1; sub(/\(\).*/, "", fn)
      s = ""
      for (i = 1; i <= n; i++) {
        line = block[i]
        sub(/^#[ \t]?/, "", line)
        sub(/^[ \t]+/, "", line); sub(/[ \t]+$/, "", line)
        if (line == "") continue
        sub("^" fn "[:-]?[ \t]*", "", line)
        sub(/^[-:][ \t]*/, "", line)
        if (line == "") continue
        s = line
        break
      }
      f = FILENAME; sub(/^\.\//, "", f)
      printf "%s\t%s\t%s\n", fn, f, s
      n = 0; next
    }
    /^#/ { if (!wascomment) n = 0; n++; block[n] = $0; wascomment = 1; next }
    { wascomment = 0; n = 0 }
  ' $FILES
}

# accepted <file>: the case labels of a *_check function, as a code fence
#
# the awk/sed programs below are single-quoted on purpose; $1 and \1 belong to
# them, not to the shell
# shellcheck disable=SC2016
accepted() {
  printf '```\n'
  grep -oE '^[[:space:]]+[a-z0-9]+\)' "$1" | tr -d ' )' | sort | tr '\n' ' '
  printf '\n```\n'
}

# mappings <file>: the `pattern) var="value"` fixups, as a table
# shellcheck disable=SC2016
mappings() {
  printf '| `uname -m` reports | mapped to |\n| --- | --- |\n'
  sed -n 's/^[[:space:]]*\([a-z0-9*_]*\))[[:space:]]*_shlib_arch="\([a-z0-9]*\)".*/| `\1` | `\2` |/p' "$1"
}

undocumented=$(extract | awk -F'\t' '$3 == "" { print "  " $1 " (" $2 ")" }')
if [ -n "$undocumented" ]; then
  echo "mkapi: these functions have no summary comment:" >&2
  echo "$undocumented" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"
{
  cat <<'HEADER'
# Function index

Generated by `make docs` from the comment above each function -- do not edit
this file by hand.

This is an index. Arguments, return values and side effects are documented in
the source comments, which each row links to.

Installer functions are not listed here: they are internal to a generated
install script and are covered by [INSTALLERS.md](INSTALLERS.md).

| function | summary |
| -------- | ------- |
HEADER
  extract | sort | awk -F'\t' '{ printf "| [`%s`](../%s) | %s |\n", $1, $2, $3 }'
  echo
  printf '%s functions.\n' "$(extract | wc -l | tr -d ' ')"

  cat <<'PLATHEAD'

## Platforms

`uname_os` and `uname_arch` translate what `uname` reports into Go's GOOS and
GOARCH names, which are what release artifacts are almost always named after.
The lists below are extracted from `uname_os_check.sh` and `uname_arch_check.sh`.

### Recognised operating systems

PLATHEAD
  accepted uname_os_check.sh
  cat <<'PLATOS'

Most values come straight from a lowercased `uname -s`. These do not:

| `uname -s` reports | mapped to | why |
| ------------------ | --------- | --- |
| `MSYS_NT-*`, `MINGW*`, `CYGWIN_NT-*`, `Windows_NT` | `windows` | the Unix-ish environments on Windows each report their own name |
| `SunOS` with `uname -o` = `illumos` | `illumos` | illumos and Solaris both still report the ancient `SunOS` |
| `SunOS` otherwise | `solaris` | Oracle Solaris; its `uname` has no `-o`, so the check is silent about it |

`sunos` itself is deliberately never returned -- it is not a GOOS value.

### Recognised architectures

PLATOS
  accepted uname_arch_check.sh
  cat <<'PLATARCH'

Mapped from `uname -m`:

PLATARCH
  mappings uname_arch.sh
} >"$OUT"

echo "mkapi: wrote $OUT ($(extract | wc -l | tr -d ' ') functions)"
